# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    target-branch: "master"
    open-pull-requests-limit: 0
    
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    target-branch: "master"
    open-pull-requests-limit: 0
